import { createFileRoute, Link } from "@tanstack/react-router";
import { AppShell, PageHeader } from "@/components/app-shell";
import { CategoryBadge } from "@/components/email-bits";
import { useState } from "react";
import { ChevronDown, FileText, Sparkles } from "lucide-react";
import { emails, threads } from "@/lib/mock-data";
import { format } from "date-fns";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_app/summaries")({
  head: () => ({ meta: [{ title: "Summaries — Repeatless AI" }] }),
  component: Summaries,
});

type Item = {
  id: string;
  title: string;
  summary: string;
  date: string;
  category: any;
  source: string;
  threadId: string;
};

function Summaries() {
  const [tab, setTab] = useState<"thread" | "email">("thread");
  const items: Item[] =
    tab === "thread"
      ? threads.map((t) => ({
          id: t.id,
          title: t.subject,
          summary: t.summary,
          date: t.lastActivity,
          category: t.category,
          source: `${t.messages.length} messages · ${t.participants.length} people`,
          threadId: t.id,
        }))
      : emails
          .filter((e) => e.summary)
          .map((e) => ({
            id: e.id,
            title: e.subject,
            summary: e.summary!,
            date: e.date,
            category: e.category,
            source: e.senderName,
            threadId: e.threadId,
          }));

  return (
    <AppShell title="Summaries">
      <PageHeader
        eyebrow="AI synthesis"
        title="Summaries"
        description="Thread-level and email-level summaries generated by Gemini. Click any to open the source."
      />

      <div className="mb-5 inline-flex gap-1 rounded-xl border border-border bg-card p-1">
        {(["thread", "email"] as const).map((k) => (
          <button
            key={k}
            onClick={() => setTab(k)}
            className={cn(
              "rounded-lg px-3 py-1.5 text-sm font-medium capitalize transition-colors",
              tab === k ? "bg-navy text-ivory" : "text-charcoal-soft hover:text-charcoal",
            )}
          >
            {k} summaries
          </button>
        ))}
      </div>

      <div className="space-y-3">
        {items.map((item) => (
          <SummaryCard key={item.id} item={item} />
        ))}
      </div>
    </AppShell>
  );
}

function SummaryCard({ item }: { item: Item }) {
  const [open, setOpen] = useState(true);
  return (
    <div className="surface-card overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="flex w-full items-start gap-4 p-5 text-left hover:bg-beige/40"
      >
        <div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-beige">
          <Sparkles className="h-4 w-4 text-forest" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <CategoryBadge category={item.category} />
            <span className="text-xs text-muted-foreground">{item.source}</span>
          </div>
          <div className="mt-1 font-serif text-base font-semibold text-charcoal">{item.title}</div>
        </div>
        <ChevronDown
          className={cn(
            "mt-1 h-4 w-4 shrink-0 text-muted-foreground transition-transform",
            open && "rotate-180",
          )}
        />
      </button>
      {open && (
        <div className="border-t border-border bg-parchment/30 px-5 py-4">
          <p className="text-[14.5px] leading-relaxed text-charcoal">{item.summary}</p>
          <div className="mt-4 flex items-center justify-between text-xs text-muted-foreground">
            <div className="flex items-center gap-2">
              <FileText className="h-3.5 w-3.5" />
              Source · {format(new Date(item.date), "PPp")}
            </div>
            <Link
              to="/threads/$threadId"
              params={{ threadId: item.threadId }}
              className="text-navy hover:underline"
            >
              Open source →
            </Link>
          </div>
        </div>
      )}
    </div>
  );
}
