/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSummariesRouteImport } from './routes/_app.summaries'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppNewslettersRouteImport } from './routes/_app.newsletters'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppComposeRouteImport } from './routes/_app.compose'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppAgentRouteImport } from './routes/_app.agent'
import { Route as AppThreadsIndexRouteImport } from './routes/_app.threads.index'
import { Route as AppThreadsThreadIdRouteImport } from './routes/_app.threads.$threadId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSummariesRoute = AppSummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppNewslettersRoute = AppNewslettersRouteImport.update({
  id: '/newsletters',
  path: '/newsletters',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComposeRoute = AppComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadsIndexRoute = AppThreadsIndexRouteImport.update({
  id: '/threads/',
  path: '/threads/',
  getParentRoute: () => AppRoute,
} as any)
const AppThreadsThreadIdRoute = AppThreadsThreadIdRouteImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/agent': typeof AppAgentRoute
  '/categories': typeof AppCategoriesRoute
  '/compose': typeof AppComposeRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/newsletters': typeof AppNewslettersRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/summaries': typeof AppSummariesRoute
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/threads/': typeof AppThreadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/agent': typeof AppAgentRoute
  '/categories': typeof AppCategoriesRoute
  '/compose': typeof AppComposeRoute
  '/dashboard': typeof AppDashboardRoute
  '/inbox': typeof AppInboxRoute
  '/newsletters': typeof AppNewslettersRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/summaries': typeof AppSummariesRoute
  '/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/threads': typeof AppThreadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/connect': typeof ConnectRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/compose': typeof AppComposeRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/newsletters': typeof AppNewslettersRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/summaries': typeof AppSummariesRoute
  '/_app/threads/$threadId': typeof AppThreadsThreadIdRoute
  '/_app/threads/': typeof AppThreadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/oauth-callback'
    | '/signin'
    | '/signup'
    | '/agent'
    | '/categories'
    | '/compose'
    | '/dashboard'
    | '/inbox'
    | '/newsletters'
    | '/search'
    | '/settings'
    | '/summaries'
    | '/threads/$threadId'
    | '/threads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/oauth-callback'
    | '/signin'
    | '/signup'
    | '/agent'
    | '/categories'
    | '/compose'
    | '/dashboard'
    | '/inbox'
    | '/newsletters'
    | '/search'
    | '/settings'
    | '/summaries'
    | '/threads/$threadId'
    | '/threads'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/connect'
    | '/oauth-callback'
    | '/signin'
    | '/signup'
    | '/_app/agent'
    | '/_app/categories'
    | '/_app/compose'
    | '/_app/dashboard'
    | '/_app/inbox'
    | '/_app/newsletters'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/summaries'
    | '/_app/threads/$threadId'
    | '/_app/threads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/summaries': {
      id: '/_app/summaries'
      path: '/summaries'
      fullPath: '/summaries'
      preLoaderRoute: typeof AppSummariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/newsletters': {
      id: '/_app/newsletters'
      path: '/newsletters'
      fullPath: '/newsletters'
      preLoaderRoute: typeof AppNewslettersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compose': {
      id: '/_app/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof AppComposeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threads/': {
      id: '/_app/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof AppThreadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threads/$threadId': {
      id: '/_app/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof AppThreadsThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppComposeRoute: typeof AppComposeRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInboxRoute: typeof AppInboxRoute
  AppNewslettersRoute: typeof AppNewslettersRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSummariesRoute: typeof AppSummariesRoute
  AppThreadsThreadIdRoute: typeof AppThreadsThreadIdRoute
  AppThreadsIndexRoute: typeof AppThreadsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppComposeRoute: AppComposeRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInboxRoute: AppInboxRoute,
  AppNewslettersRoute: AppNewslettersRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSummariesRoute: AppSummariesRoute,
  AppThreadsThreadIdRoute: AppThreadsThreadIdRoute,
  AppThreadsIndexRoute: AppThreadsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConnectRoute: ConnectRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
